name: CIT Kafka

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  kafka:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3.1.0

    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16

    - name: Run kafka integration tests
      run: bash scripts/kafka-integration-test.sh
